### ISSUE TITLE
Internal Search

### ISSUE THREAD

**Issue by marcelosambaderaiz** [antonlukin/instapress#4]
Hello. I installed the Instapress theme and I'm really enjoying it. I have two questions: 1. Do you intend to update the theme? 2. How to enter an internal search? Regards, Marcelo

**Comment by antonlukin** [comment]
Hello, @marcelosambaderaiz. Missed your message, sorry.
I will keep track of security issues and update based on the WordPress recommendations but I don't intend to introduce new functionality yet.

To enter internal search, just create new page and select "Search page" template in post attributes metabox

<img width="296" alt="search" src="https://user-images.githubusercontent.com/454185/82756154-71c68d80-9de9-11ea-8ff0-4d2afc499a16.png">

You will get a page similar to this:  
https://lukin.blog/search/

**Comment by marcelosambaderaiz** [comment]
Thanks for answering. I will create the page with the search. I asked about the updates because I liked the theme and I don't intend to change it anytime soon. There are themes that the developer creates and never does anything again. You don't care about security. I'm glad that's not your case. My blog is not focused on photographs, on the contrary, but I really like simplicity and speed and the Instapress theme is perfect for me. I'm from Brazil and my blog is on this link: 

https://sambaderaiz.org

Thanks again.
